name: ESP32 Build

on:
  push:
    branches: [ main, develop ]
    paths: [ 'esp32/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'esp32/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build firmware
      run: |
        cd esp32
        pio run
    
    - name: Run tests
      run: |
        cd esp32
        pio test -e native
    
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: esp32-firmware
        path: esp32/.pio/build/esp32/firmware.bin 